-- AlterTable
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "logo" TEXT;
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "region" TEXT;
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'GHS';
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "default_delivery_fee" DOUBLE PRECISION;
